# ==========================================================
#     File di Configurazione di Netlify (Versione Semplificata)
# ==========================================================
# Questo file definisce solo il comando di build che genera
# il file firebase-config.js dal template.
#
# Le variabili d'ambiente (apiKey, projectId, etc.) devono
# essere definite nell'interfaccia di Netlify per ogni sito
# (produzione e test) in modo che ognuno usi le chiavi corrette.

[build]
  command = "cp firebase-config.js.template firebase-config.js && sed -i 's|__FIREBASE_API_KEY__|'\"$apiKey\"'|g' firebase-config.js && sed -i 's|__FIREBASE_AUTH_DOMAIN__|'\"$authDomain\"'|g' firebase-config.js && sed -i 's|__FIREBASE_PROJECT_ID__|'\"$PROJECT_ID\"'|g' firebase-config.js && sed -i 's|__FIREBASE_STORAGE_BUCKET__|'\"$STORAGE_BUCKET\"'|g' firebase-config.js && sed -i 's|__FIREBASE_MESSAGING_SENDER_ID__|'\"$messagingSenderId\"'|g' firebase-config.js && sed -i 's|__FIREBASE_APP_ID__|'\"$appId\"'|g' firebase-config.js"
