# ==========================================================
#     File di Configurazione Globale di Netlify (con Build Command)
# ==========================================================

# Questa sezione definisce un comando da eseguire durante il deploy
[build]
  command = "cp firebase-config.js.template firebase-config.js && sed -i 's|__FIREBASE_API_KEY__|'\"$apiKey\"'|g' firebase-config.js && sed -i 's|__FIREBASE_AUTH_DOMAIN__|'\"$authDomain\"'|g' firebase-config.js && sed -i 's|__FIREBASE_PROJECT_ID__|'\"$PROJECT_ID\"'|g' firebase-config.js && sed -i 's|__FIREBASE_STORAGE_BUCKET__|'\"$STORAGE_BUCKET\"'|g' firebase-config.js && sed -i 's|__FIREBASE_MESSAGING_SENDER_ID__|'\"$messagingSenderId\"'|g' firebase-config.js && sed -i 's|__FIREBASE_APP_ID__|'\"$appId\"'|g' firebase-config.js"

# --- Configurazione per il sito di PRODUZIONE (branch 'main') ---
[context.production.environment]
  apiKey = "AIzaSyC_gm-MK5dk2jc_MmmwO7TWBm7oW_D5t1Y"
  authDomain = "consorzio-artigiani-idraulici.firebaseapp.com"
  PROJECT_ID = "consorzio-artigiani-idraulici"
  STORAGE_BUCKET = "consorzio-artigiani-idraulici.firebasestorage.app"
  messagingSenderId = "136848104008"
  appId = "1:136848104008:web:2724f60607dbe91d09d67d"

# --- Configurazione per i DEPLOY DI TEST (branch 'CAI-TEST') ---
[context.branch-deploy.environment]
  apiKey = "AIzaSyCccw1e4CAV9voUzHpKQRDyicUG7Mc_Q2U"
  authDomain = "cai-test-4e97e.firebaseapp.com"
  PROJECT_ID = "cai-test-4e97e"
  STORAGE_BUCKET = "cai-test-4e97e.firebasestorage.app"
  messagingSenderId = "212585761230"
  appId = "1:212585761230:web:dda0a06fa85f7dfb7b839f"
